// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "2106ba28-8f05-4907-a073-9f81c1404c32");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1554813644);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1554814908);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1554812506);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1554809146);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1554809026);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1554813524);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1554727604);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1554815028);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1554650666);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"36649\":1554726978681,\"36671\":1554808887331,\"36678\":1554808887331,\"36694\":1554815227574,\"36696\":1554809311395,\"36707\":1554809311395,\"36709\":1554815227574,\"36713\":1554809311395,\"36715\":1554815227574}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{546840b3-1d59-4f94-86bc-df1abc435900}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1554778800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 1);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1554814889701");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1554816712701");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1554812492795");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1554816092795");
user_pref("browser.search.region", "CA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190327091201");
user_pref("browser.slowStartup.averageTime", 10067);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190327091201");
user_pref("browser.startup.homepage_override.mstone", "66.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1554650674490");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "e6383dfce6bc4f58838015eb9518aabd");
user_pref("extensions.blocklist.lastModified", "Mon, 08 Apr 2019 20:27:53 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1554813645);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190327091201");
user_pref("extensions.lastAppVersion", "66.0.2");
user_pref("extensions.lastPlatformVersion", "66.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{a9797bc9-80ac-4451-99f9-ed29297507fa}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"69330b27-924b-465c-b0a5-3259259a534d\",\"screenshots@mozilla.org\":\"304dcd0c-835e-4ef5-a968-23bed690dc1b\",\"webcompat-reporter@mozilla.org\":\"78b572ef-aca7-4424-ab60-8da7ba3ee2ae\",\"webcompat@mozilla.org\":\"41b9b6f4-5a6c-4cef-810c-30d6d0137e52\",\"fxmonitor@mozilla.org\":\"4fec89b9-3f94-46ff-a78b-74979d4a1724\"}");
user_pref("idle.lastDailyNotification", 1554727794);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1554727009);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190327091201");
user_pref("media.gmp-manager.lastCheck", 1554814930);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1554727794);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "e5702651-f0f1-4019-8099-0cfe06675065");
user_pref("security.sandbox.plugin.tempDirSuffix", "d56e319c-ceec-41a5-aee0-c23893cfcef1");
user_pref("services.blocklist.addons.checked", 1554813523);
user_pref("services.blocklist.gfx.checked", 1554813523);
user_pref("services.blocklist.onecrl.checked", 1554813523);
user_pref("services.blocklist.pinning.checked", 1554813523);
user_pref("services.blocklist.plugins.checked", 1554813523);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_update_seconds", 1554813523);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1554813523);
user_pref("services.settings.main.language-dictionaries.last_check", 1554813523);
user_pref("services.settings.main.onboarding.last_check", 1554813523);
user_pref("services.settings.main.sites-classification.last_check", 1554813523);
user_pref("services.settings.main.tippytop.last_check", 1554813523);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1554727794);
user_pref("toolkit.startup.last_success", 1554814873);
user_pref("toolkit.telemetry.cachedClientID", "2795a0ef-e60b-49cb-8bcc-1765a5b39b39");
user_pref("toolkit.telemetry.previousBuildID", "20190327091201");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
